export PATH=~/bin:/usr/local/bin:/usr/local/sbin:$PATH:$HOME/.rvm/bin

source ~/.bash/colors
export LSCOLORS="ExGxBxDxCxEgEdxbxgxcxd"

PS1='\e[37;1m\u@\e[35m\W\e[0m\$ '

export HISTCONTROL=erasedups
# Store 10k history entries
export HISTSIZE=10000
# Append to the history file when exiting instead of overwriting it
shopt -s histappend

source ~/.bash/functions
source ~/.bash/aliases

# disable flow control (ctrl-s)
stty -ixoff
stty stop undef
stty start undef

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
[[ -r $rvm_path/scripts/completion ]] && . $rvm_path/scripts/completion

export EDITOR="vim"
